version: "3.7"

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  server:
#    image: passnet-auth:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        ENV: production
    container_name: passnet-auth-server
    networks:
      mynetwork:
        ipv4_address: 172.20.0.12
    ports:
      - "1323:1323"
    depends_on:
      - db

  db:
    image: mongo
    container_name: passnet-auth-db
    environment:
      - MONGO_INITDB_DATABASE=passnet_auth
      - MONGO_INITDB_ROOT_USERNAME=passnet-auth-app
      - MONGO_INITDB_ROOT_PASSWORD=tungduong98
    ports:
      - "27019:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      mynetwork:
        ipv4_address: 172.20.0.11