version: '3'
tasks:
  set-env:
    cmds:
      - export PATH=$PATH:/usr/local/go/bin
  get-plugins:
    cmds:
      - go get github.com/golang/protobuf/protoc-gen-go
      - go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.0
  run-dev:
    cmds:
      - ENV=development go run src/main/main.go
  run-vagrant:
    cmds:
      - ENV=vagrant go run src/main/main.go
  run-prod:
    cmds:
      - ENV=production go run src/main/main.go
  first-gen-proto:
    cmds:
      - mkdir src/main/gen
      - protoc --go_out=plugins=grpc:src/main/gen src/main/proto/*.proto
  gen-proto:
    cmds:
      - rm -rf src/main/gen/*
      - protoc --go_out=plugins=grpc:src/main/gen src/main/proto/*.proto
  build:
    cmds:
      - ENV=vagrant go build src/main/main.go
  run-build:
    cmds:
      - ENV=vagrant ./main