version: '3'
tasks:
  run-dev:
    cmds:
      - ENV=development GRPC_SAGA_HOST=$(task get-windows-localhost) go run src/main/main.go
  run-prod:
    cmds:
      - ENV=production go run src/main/main.go
  first-gen-proto:
    cmds:
      - mkdir src/main/gen
      - protoc --go_out=plugins=grpc:src/main/gen src/main/proto/*.proto
  gen-proto:
    cmds:
      - rm -rf src/main/gen/*
      - >
        protoc --go_out=src/main/gen --go-grpc_out=src/main/gen --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative src/main/proto/*.proto
        --go_opt=Msrc/main/proto/produce-event.proto=github.com/DuongVu98/passnet-authentication/src/main/gen
        --go_opt=Msrc/main/proto/consume-events.proto=github.com/DuongVu98/passnet-authentication/src/main/gen
  build:
    cmds:
      - ENV=development go build src/main/main.go
  run-build:
    cmds:
      - ENV=development ./main
  get-windows-localhost:
    cmds:
      - grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'